import Head from 'next/head'
import Image from 'next/image'
import SearchBox from '../components/SearchBox'
import styles from '../styles/Home.module.css'
import BeanPurchaseForm from '../components/BeanPurhcaseForm'
import { CoffeeBean } from '../api-endpoints/Endpoint Interfaces/CoffeeBean'

let beans: CoffeeBean[] = [
  {
    id:1,
    name:"Campada"
  },
  {
    id:2,
    name:"Taylor Harrogate"
  }
] 

let roastLevels = ['Light', 'Medium', 'Dark']

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      <BeanPurchaseForm
      beans={beans}
      roastLevels={roastLevels}
      />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
